# created dummy data frame for testing
TestCampdata <- data.frame(
  IMO_ID = c("1.a.1","1.a.2","1.b.1","1.c.1","2.a.1", "2.b.1", "2.c.1", "2.d.1","2.e.1","2.f.1","3.a.1","3.b.1","3.c.1","3.c.2","3.c.3","3.c.4"),
  IMO_Name = c("Get Robo Cop", "Develop Iron Man MOS", "Develop Thick Skin", "Be Awesome","Going Full Rambo", "Space Cyber Exercise", "HQ, HQ, HQ", "Ghost in the Machine", "Biggest Data", "Spy vs Spy", "That's a Good Cap", "Liquid Paper on a Bee","Optimus Prime at AOB","Issue Laser Guns","Plasma Armor","Mind Control"),
  IMO_Owner = c("G1","G1","HPW","Chaplain","G35","G37","G37","G35","G9","G2","G8","G8","G8","G8","G8","G8"),
  IMO_LOE = c("People","People","People","People","Win","Win","Win","Win","Win","Win","Innovate","Innovate","Innovate","Innovate","Innovate", "Innovate"),
  IMO_SubLOE =  c("manning","manning","resiliency","culture & community","Optimize for IW","Ops, Training, & Exp","C & C HQs","Value Messaging","Optimized for IA","Protection","Cap Analysis","Emerging Solutions","Transformation","Transformation","Transformation","Transformation"),
  IMO_Dep = c(c(NULL),c(NULL),c(NULL),c("1.b.1"),c(NULL),c("1.a.1","2.e.1","3.c.1"),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL),c(NULL)),
  IMO_Desciption = c("Recruiting Robo Cop to improve cross-functional teams.","Develop MOS to operated new iron man suits optimizing for IW.","Improve resiliency by developing thick skin and fostering critical feedback.","Just be awesome - enough said.","Be a good guerilla like Rambo in all 18 of the movies.","Triad exercise to test capability across the functional ASCCs.","More HQs, more Command and Control, more effects, more competition.","Make sick recruiting videos.","You have big data, we have the biggest data.","Recreated protection mechanisms as envisioned by SNL.","Analyzed capabilities if good label it as good cap, else label as bad cap.","Putting in the R&D man hours, we put liquid paper on a bee, it died.","Transform more than meets the eye, transform innovation in disguise.","Transform the formation from chemically propelled ballistics to energy weapons","Transform the formation from ballistic armor to force fields","Execute order sixty six"),
  IMO_Conditions = c(c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3"),c("1","2","3")),
  IMO_ConStat = c(c("Complete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Complete", "Incomplete", "Incomplete"),c("Compete", "Compete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Compete", "Compete", "Incomplete"),c("Compete", "Compete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Incomplete", "Incomplete", "Incomplete"),c("Complete", "Incomplete", "Incomplete")),
  IMO_Stat = c(0,0,0,0,4,4,4,0,2,1,4,2,4,4,4,4),
  IMO_OverallStat = c("Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete","Incomplete"),
  IMO_SupportedOBJ = c("Optimize for IW","Optimize for IW","","","Optimize for IW","Adaptive and Defendable Capabilities and Assets","SOJTF-C","Optimize for IA","Optimize for IA","Adaptive and Defendable Capabilities and Assets","Develop and Deliver Relevant Capabilities to the Future Force","Develop and Deliver Relevant Capabilities to the Future Force","Develop and Deliver Relevant Capabilities to the Future Force","Develop and Deliver Relevant Capabilities to the Future Force","Develop and Deliver Relevant Capabilities to the Future Force", "Develop and Deliver Relevant Capabilities to the Future Force"),
  IMO_StartDate = c("30-Oct-22","01-Nov-22","24-Oct-22","01-Jan-23","30-Oct-22","01-Jan-23","30-Oct-22","30-Oct-22","24-Oct-22","30-Oct-22","30-Oct-22","24-Oct-22","01-Jan-23","01-Jan-23","01-Jan-23", "01-Jan-23"),
  IMO_ProposedEndDate = c("13-Nov-22","03-Feb-23","12-Dec-22","02-Mar-23","13-Nov-22","02-Mar-23","13-Nov-22","13-Nov-22","12-Dec-22","13-Nov-22","13-Nov-22","12-Dec-22","02-Mar-23","02-Mar-23","02-Mar-23","02-Mar-23"),
  IMO_ActualEndDate = c("13-Nov-22","03-Feb-23","12-Dec-22","02-Mar-22","13-Nov-22","02-Mar-23","13-Nov-22","13-Nov-22","12-Dec-22","13-Nov-22","13-Nov-22","12-Dec-22","02-Mar-23","02-Mar-23","02-Mar-23","02-Mar-23")
)
